# Generated by Django 3.0.7 on 2020-06-29 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 29, 11, 21, 59, 668487, tzinfo=utc)),
        ),
    ]
